// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GDemoExpress.DataBase.Entities
{
    public partial class Player
    {
        public Guid PlayerId { get; set; }
        public string Account { get; set; } = default!;
        public string Password { get; set; } = default!;
        public int Status { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
    }
}