---
version: '3'
services:
  postgres:
    image: postgres:12.8
    container_name: postgresql-example
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1qaz2wsx
      POSTGRES_DB: example
    volumes:
    - pg_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    restart: always
  redis:
    image: redis:latest
    container_name: redis-example
    command: redis-server --requirepass 1qaz2wsx
    ports:
    - 6379:6379
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb-example
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1qaz2wsx
    ports:
    - 27017:27017
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mongodb-example-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1qaz2wsx
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1qaz2wsx
    ports:
    - 8081:8081
volumes:
  pg_data:
