// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GDemoExpress.DataBase.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace GDemoExpress.DataBase.Entities.Configurations
{
    public partial class PlayerinfoConfiguration : IEntityTypeConfiguration<Playerinfo>
    {
        public void Configure(EntityTypeBuilder<Playerinfo> entity)
        {
            entity.HasKey(e => e.PlayerId)
                .HasName("playerinfos_pk");

            entity.ToTable("playerinfos", "dbo");

            entity.Property(e => e.PlayerId)
                .ValueGeneratedNever()
                .HasColumnName("player_id");

            entity.Property(e => e.FullName)
                .HasMaxLength(32)
                .HasColumnName("full_name");

            entity.Property(e => e.LastName)
                .HasMaxLength(32)
                .HasColumnName("last_name");

            entity.Property(e => e.Mailbox)
                .HasMaxLength(128)
                .HasColumnName("mailbox");

            entity.Property(e => e.NickName)
                .HasMaxLength(32)
                .HasColumnName("nick_name");

            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .HasColumnName("phone_number");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Playerinfo> entity);
    }
}
