// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GDemoExpress.DataBase.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace GDemoExpress.DataBase.Entities.Configurations
{
    public partial class PlayerConfiguration : IEntityTypeConfiguration<Player>
    {
        public void Configure(EntityTypeBuilder<Player> entity)
        {
            entity.ToTable("players", "dbo");

            entity.HasIndex(e => e.Account, "players_account_idx")
                .IsUnique();

            entity.Property(e => e.PlayerId)
                .ValueGeneratedNever()
                .HasColumnName("player_id");

            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnName("account");

            entity.Property(e => e.CreatedOn)
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_on")
                .HasDefaultValueSql("now()");

            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("password");

            entity.Property(e => e.Status)
                .HasColumnName("status")
                .HasDefaultValueSql("1");

            entity.Property(e => e.UpdatedOn)
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_on")
                .HasDefaultValueSql("now()");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Player> entity);
    }
}
