// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GDemoExpress.DataBase.Entities.Configurations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
#nullable enable

#nullable disable

namespace GDemoExpress.DataBase.Entities
{
    public partial class DboContext : DbContext
    {
        public DboContext()
        {
        }

        public DboContext(DbContextOptions<DboContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Playerinfo> Playerinfos { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasPostgresExtension("uuid-ossp")
                .HasAnnotation("Relational:Collation", "en_US.utf8");

            modelBuilder.ApplyConfiguration(new Configurations.PlayerConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PlayerinfoConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
