// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GDemoExpress.DataBase.Entities
{
    public partial class Playerinfo
    {
        public Guid PlayerId { get; set; }
        public string? LastName { get; set; }
        public string? FullName { get; set; }
        public string? NickName { get; set; }
        public string? PhoneNumber { get; set; }
        public string? Mailbox { get; set; }
    }
}